openapi: 3.0.3
info: 
  title: DaB Integration with ContentFlow (CMS)
  description: |
   ## About API
    Using this `OpenAPI specification`, any Assets Management System can understand the _APIs_ that are exposed by the ***FoC*** team to push Assets to ContentFlow.
  x-custom-info:
    comment: some comments
    authors:
      - name: XYZ
        email: xya@abc.com
  contact: 
    name: FoC Support
    email: hem.kant@adidas.com
  version: 0.0.1
servers: 
  - url: https://dev.api.com/v1/
    description: Devlopment API
  - url: https://qa.api.com/v1/
    description: QA API
  - url: https://api.com/v1/
    description: PROD API
  - url: https://{username}.api.com:{port}/{version}
    variables:
      username:
        default: demo
        description: this value is a default.
      port:
        enum:
          - "8080"
          - "443"
        default: "8080"
      version: 
        default: v1
paths:
  /assets:
    post:
      summary: Uplaod assets to ContentFlow (CMS).
      description: |
        Post assets for processing
      requestBody:
        content:
          multipart/form-data::
            schema:
              type: object
              properties:
                products: 
                  type: array
                  items:
                    $ref: "#/components/schemas/assets" 
      responses:
        '201':
          description: Assets uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  assetID:
                    type: integer
          links:
            GetOrderByOrderId:
              $ref: "#/components/links/GetOrderByOrderId"
        '500':
          $ref: "#/components/responses/InternalServerError"
components:
  parameters:
    orderIdQueryParam:
      name: orderId
      in: query
      required: true
      schema:
        type: integer
  schemas:
    assets:
      type: object
      properties:
        assetID:
          type: integer
        assetName:
          type: string
        assetsPath:
          type: string 
        releseDate:
          type: string
          format: date
          readOnly: true
  responses:
    InternalServerError:
      description: |
        ### An error has occured please contant hem.kant@adidas.com for assistance
  links:
    GetOrderByOrderId:
      description: >
        * The `orderId` value returned in the response can be used as a input paramter in `GET /orders`.
      operationId: getProductdetails
      parameters:
        orderId: '$response.body#/orderId'
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

          

      
      
      
      
      
      
