openapi: 3.0.3
info: 
  title: Shop Online APIs Definition - demo
  description: |
   ## About API
    Using this `OpenAPI specification`, any DAB can understand the _APIs_ that are exposed by the ***FoC*** team to push Assets to ContentFlow.
  x-custom-info:
    comment: some comments
    authors:
      - name: XYZ
        email: xya@abc.com
  contact: 
    name: FoC Support
    email: hem.kant@adidas.com
  version: 0.0.1
servers: 
  - url: https://dev.api.com/v1/
    description: Devlopment API
  - url: https://qa.api.com/v1/
    description: QA API
  - url: https://api.com/v1/
    description: PROD API
  - url: https://{username}.api.com:{port}/{version}
    variables:
      username:
        default: demo
        description: this value is a default.
      port:
        enum:
          - "8080"
          - "443"
        default: "8080"
      version: 
        default: v1

      
      
      
      
      
      
